name: CI Checks

on:
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1

jobs:
  lint-and-unit-test:
    name: Lint and Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.60.3
          args: --out-format checkstyle:lint-report.xml,github-actions --timeout 5m
      - name: Run unit tests
        run: RUN_IN_DOCKER='' make tests-unit
      - name: Set env
        run: echo "ARTIFACT_NAME=$(echo $GITHUB_REF | tr '/' '-')" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ env.ARTIFACT_NAME }}-unit
          path: |
            test/coverage-unit
          retention-days: 1
          overwrite: true

  terraform-format:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform
