name: Deploy Infrastructure

on:
  workflow_call:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/infra.yml'

env:
  AWS_REGION: ap-southeast-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Build and make zip
        run: |
          make make-zip
          ls -la app.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/development

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/environments/development
        env:
          TF_VAR_lambda_zip_path: "${{ github.workspace }}/app.zip"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: terraform/environments/development
        env:
          TF_VAR_lambda_zip_path: "${{ github.workspace }}/app.zip"